### ISSUE TITLE
Fix broken links to data assembly python notebooks 

### ISSUE THREAD

**Issue by aloraine** [griffithlab/DeepSVR#11]
Links to python notebooks on page https://github.com/griffithlab/DeepSVR/wiki/Data-Assembly give 404 file not found errors.

Broken links:

- https://github.com/griffithlab/DeepSVR/blob/master/notebooks/Add%20project%20specific%20features.ipynb

- https://github.com/griffithlab/DeepSVR/blob/master/notebooks/Duplicate%20analysis.ipynb

- https://github.com/griffithlab/DeepSVR/blob/master/notebooks/parse%20bam%20read%20count.ipynb

**Comment by ebarnell** [comment]
Hi @aloraine I apologize for the broken links. Prior to releasing the database we had to remove some data for compliance reasons, therefore, the dataframes and notebooks used to generate the prepared data from raw data were removed. I have updated the wiki page to inform users of this change and removed the links from the wiki. If you would like to learn more about how we performed the analysis I am happy to answer any questions you might have! Sorry for the inconvenience.

Best,
Erica
