### ISSUE TITLE
nonexistent directory 'create_classifier'

### ISSUE THREAD

**Issue by przemekl** [griffithlab/DeepSVR#8]
Wiki page https://github.com/griffithlab/DeepSVR/wiki/Create-the-Classifier contains links to nonexistent directory https://github.com/griffithlab/DeepSVR/tree/master/deepsvr/tests/test_data/create_classifier/

**Comment by ebarnell** [comment]
Thank you for bringing this to my attention. The links and directories have been restored. I tested the commands and they should be working. Please let me know if you encounter any additional problems.

**Comment by przemekl** [comment]
Indeed, thank you.
Please correct the typo in the deepsvr call on the same wiki page - 'train-classifier' not 'train_classifier', and close issue.

**Comment by ebarnell** [comment]
Hi przemekl,

According to the [usage documents ](https://github.com/griffithlab/DeepSVR/wiki/Usage-Documents), the command is listed as: deepsvr train_classifier [OPTIONS]

Did you get an error when running this command?

**Comment by bainscou** [comment]
The click package changed how it handles underscores in cli programs. I changed the wiki and am closing.
