### ISSUE TITLE
sample.review.one_based file

### ISSUE THREAD

**Issue by przemekl** [griffithlab/DeepSVR#9]
Is the sample.review.one_based file necessary for data preparation?
If so, how is it different from sample.review?

**Comment by ebarnell** [comment]
sample.review.one_based file is not necessary for data preparation. In the tutorial we exclusively use sample.review for data prep. I had used that file to test if the classifier can take in zero-based or one-based coordinates from the manual review files (it can do both!).

An explanation of one_based vs. zero_based can be found on BioStars: [Tutorial: Cheat Sheet For One-Based Vs Zero-Based Coordinate Systems](https://www.biostars.org/p/84686/)

**Comment by bainscou** [comment]
@przemekl that file is generated by prepare-data.py in the `_parse_review_file ` section called on line 87. Could you provide any more details about your specific usage? What is the general format of your samples file you are using?

**Comment by przemekl** [comment]
@bainscou please remove 'test_data/prepare_data/tst1.review.one_based' and run 'deepsvr prepare-data --header --no-skip_bam_readcount -sfp test_data/prepare_data/samples.tsv -odp inference/'

**Comment by bainscou** [comment]
This was indeed a bug. Fixed
